Framework_Light/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from catalog import views

urlpatterns = [

    path('', views.HomeView.as_view(), name='home'),
    path('<slug:slug>', cache_page(60 * 60)(views.CatalogView.as_view()), name='category'),
    path('book/<slug:slug>', views.BookView.as_view(), name='book'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('search-data/', views.SearchDataView.as_view(), name='search-data'),

    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    
    path('robots.txt', views.robots_view)
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)
    description = models.TextField()

    objects = models.Manager()

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)

    objects = models.Manager()

    def __str__(self):
        return self.name


class User(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)

    objects = models.Manager()

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    img = models.ImageField(upload_to='books_images')
    language = models.CharField(max_length=255)
    places = models.CharField(max_length=255)
    times = models.CharField(max_length=255)
    published = models.CharField(max_length=255, null=True, blank=True)

    pages = models.CharField(max_length=255)

    # ID Numbers
    openlibrary = models.CharField(max_length=255)
    archive = models.CharField(max_length=255)
    isbn10 = models.CharField(max_length=255)
    isbn13 = models.CharField(max_length=255)

    img_source = models.URLField(max_length=255, null=True)
    book_source = models.URLField(max_length=255, null=True, blank=True)

    parsing_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    categs = models.ManyToManyField(Category)
    authors = models.ManyToManyField(Author)
    users = models.ManyToManyField(User)

    objects = models.Manager()

    def __str__(self):
        return self.name


class Reviews(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    email = models.EmailField()
    comment = models.TextField()
    rating = models.IntegerField()
    published = models.DateTimeField(auto_now_add=True)
    moderated = models.BooleanField(default=False)

    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    objects = models.Manager()

    def __str__(self):
        return self.name

catalog/views.py
import logging
from django.shortcuts import render
from django.http import Http404
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.detail import SingleObjectMixin
from django.db.models import Count
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect

from django.contrib import messages

from .models import *


logger = logging.getLogger('django')


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        len_books = Book.objects.all()
        len_authors = Author.objects.all()
        len_users = User.objects.all()
        romance_books = Book.objects.all()[142:150]  # .filter(name__contains = 'romance'  [in stock 3 books])
        fantasy_books = Book.objects.all()[240:248]
        history_books = Book.objects.all()[32:40]
        biographies_books = Book.objects.all()[332:340]
        context.update({
            'len_books': len_books,
            'len_authors': len_authors,
            'len_users': len_users,
            'romance_books': romance_books,
            'fantasy_books': fantasy_books,
            'history_books': history_books,
            'biographies_books': biographies_books,
        })

        logger.debug(context)

        return context


class CatalogView(ListView, SingleObjectMixin):
    template_name = 'catalog.html'
    model = Book
    paginate_by = 9

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(
            queryset=Category.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        author = self.request.GET.get('author')
        if author:
            return Book.objects.filter(authors__slug=author)
        return Book.objects.filter(categs=self.object)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_authors'] = Author.objects.annotate(books_count=Count('book')).order_by('-books_count')[:22]
        return context


@method_decorator(csrf_protect, name='dispatch')
class BookView(DetailView):
    template_name = 'book.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['related_books'] = Book.objects.all()[:4]
        context['reviews'] = Reviews.objects.filter(
            book=self.object, moderated=True).order_by('-published')[:10]
        return context

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        data = self.request.POST
        review = {
            'name': data['name'],
            'email': data['email'],
            'comment': data['comment'],
            'rating': data['rating'],
            'book': self.object
        }
        Reviews.objects.create(**review)
        messages.add_message(
            self.request, messages.INFO,
            'Thanks! Your review is on moderation.'
        )

        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class SearchView(ListView):
    template_name = 'catalog.html'
    model = Book
    paginate_by = 9

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query.isdigit():
            return Book.objects.filter(published__contains=query)
        elif query:
            return Book.objects.filter(name__contains=query)
        else:
            return Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_authors'] = Author.objects.annotate(books_count=Count('book')).order_by('-books_count')[:22]
        return context


class SearchDataView(ListView):
    template_name = 'catalog.html'
    model = Book
    paginate_by = 9

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Book.objects.filter(published__contains=query)
        else:
            return Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_authors'] = Author.objects.annotate(books_count=Count('book')).order_by('-books_count')[:22]
        return context



def robots_view(request):
    return render(request, 'robots.txt', {}, content_type="text/plain")

templates/banner.html
<div class="kode-inner-banner">
    <div class="kode-page-heading">
        <h2>Welcome!</h2>
        <ol class="breadcrumb">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="#">Library</a></li>
        </ol>
    </div>
</div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>Book Library - Book Guide Author, Publication and Store</title>
<!-- CUSTOM STYLE -->
<link href="{% static 'style.css' %}" rel="stylesheet">
<!-- THEME TYPO -->
<link href="{% static 'css/themetypo.css' %}" rel="stylesheet">
<!-- BOOTSTRAP -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<!-- COLOR FILE -->
<link href="{% static 'css/color.css' %}" rel="stylesheet">
<!-- FONT AWESOME -->
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
<!-- BX SLIDER -->
<link href="{% static 'css/bxslider.css' %}" rel="stylesheet">
<!-- Boostrap Slider -->
<link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">
<!-- Widgets -->
<link href="{% static 'css/widget.css' %}" rel="stylesheet">
<!-- Owl Carusel -->
<link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
<!-- responsive -->
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
<!-- Component -->
<link href="{% static 'js/dl-menu/component.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/bookblock.css' %}" />
<!-- Custom rating -->
<link href="{% static 'css/custom.css' %}" rel="stylesheet">


<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<![endif]-->
</head>
<body>
<div id="loader-wrapper">
	<div id="loader"></div>

	<div class="loader-section section-left"></div>
	<div class="loader-section section-right"></div>

</div>
<!--WRAPPER START-->
<div class="wrapper">

	<!--HEADER START-->
	{% include 'header.html' %}
    <!--HEADER END-->

    <!--BANNER START-->
    {% include 'banner.html' %}
    <!--BANNER END-->

    <!--BUT NOW START-->
    {% include 'search_section.html' %}
	<!--BUT NOW END-->

    <!--CONTENT START-->
	{% block main %}{% endblock main %}
    <!--CONTENT END-->

    {% include 'footer.html' %}

</div>
<!--WRAPPER END-->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/modernizr.custom.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.bxslider.min.js' %}"></script>
<script src="{% static 'js/bootstrap-slider.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.js' %}"></script>
<script src="{% static 'js/dl-menu/modernizr.custom.js' %}"></script>
<script src="{% static 'js/dl-menu/jquery.dlmenu.js' %}"></script>
<script src="{% static 'js/jquerypp.custom.js' %}"></script>
<script src="{% static 'js/jquery.bookblock.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

templates/book.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<div class="kode-content padding-tb-50">
    <div class="container">
            {% if messages %}
            <br><br>
            {% for message in messages %}
            <p class="alert alert-success" role="alert">
              {{ message }}
            </p>
            {% endfor %}
            <br><br>
            {% endif %}
        <div class="row">
            <div class="col-md-13">
                <!--BOOK DETAIL START-->
                <div class="lib-book-detail">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="kode-thumb">
                                <img src="{{ book.img.url }}" alt="{{ book.name }}"
                                    style="width: 306px; height:460px;">
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="kode-text">
                                <h2>{{ book.name }}</h2>
                                <div class="product-review">
                                    <div class="rating">
                                        <span>☆</span><span>☆</span><span>☆</span><span>☆</span><span>☆</span>
                                    </div>
                                    <p>{{ reviews.count }} reviews</p>
                                </div>
                                <div
                                    <p>Author : <span class="color">{{ book.users.all|cut:"<QuerySet [<User: "|cut:">]>"|cut:"<QuerySet []>" }}</span></p>
                                </div>
                                <div class="book-text">
                                    <p>{{ book.description | safe | cut:"Can you add one?" | truncatechars_html:145 }}</p>
                                </div>
                                <div class="book-text">
                                    <p>Published: {{ book.published }}.</p>
                                    <p>Language: {{ book.language }}</p>
                                    <p>Author: {{ book.authors.all | cut:"<QuerySet [<Author: " | cut:">]>" | cut:"<QuerySet []>"}}.</p>
                                    <p>Categories: {{ book.categs.all | cut:"<QuerySet [" | cut:"<Category: " | cut:">" | cut:"]" | truncatechars:100 }}</p>
                                    <p>Places: {{ book.places }}</p>
                                    <p>Times: {{ book.times }}</p>
                                    <p>Pages: {{ book.pages }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--BOOK DETAIL END-->
                <!--PRODUCT REVIEW TABS START-->
                <div class="product-review-tabs">
            <!--NAV TABS START-->
            <ul class="nav nav-tabs" role="tablist">
                {% if reviews %}
                <li role="presentation"><a href="books-detail.html#reviews" aria-controls="reviews" role="tab" data-toggle="tab">Reviews</a></li>
                {% endif %}
                <li role="presentation"><a href="books-detail.html#tags" aria-controls="tags" role="tab" data-toggle="tab">Categories</a></li>
                <li role="presentation" class="active"><a href="books-detail.html#CustomTab" aria-controls="CustomTab" role="tab" data-toggle="tab">Descriptions</a></li>
                <li role="presentation"><a href="books-detail.html#ID" aria-controls="ID" role="tab" data-toggle="tab">ID numbers</a></li>
            </ul>
            <!--NAV TABS END-->
            <!--TAB PANEL START-->
            <div class="tab-content">
                {% if reviews %}
                <div role="tabpanel" class="tab-pane fade" id="reviews">
                    <div class="kode-comments">
                        {% for review in reviews %}
                        <div>
                            <div class="rateyo"
                                 data-rateyo-rating="{{ review.rating }}"
                                 data-rateyo-num-stars="5"></div>
                        </div>
                        <div class="kode-text">
                            <h4>{{ review.name }}</h4>
                            <p class="designation">{{ review.published }}</p>
                            <p>{{ review.comment | safe }}</p>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
                <div role="tabpanel" class="tab-pane fade" id="tags">
                     <div class="product-tags">
                            {% for cat in book.categs.all %}
                            <a href="{% url 'category' cat.slug %}#">{{ cat }}</a>
                            {% endfor %}
                     </div>
                </div>
                    <div role="tabpanel" class="tab-pane fade in active" id="CustomTab">
                        <p>{{ book.description | safe | cut:" Can you add one?" }}</p>
                    </div>
                <div role="tabpanel" class="tab-pane fade" id="ID">
                    <p>Openlibrary: {{ book.openlibrary }}</p>
                    <p>Archive: {{ book.archive }}</p>
                    <p>ISBN 10: {{ book.isbn10 }}</p>
                    <p>ISBN 13: {{ book.isbn13 }}</p>
                </div>
            </div>
            <!--TAB PANEL END-->
        </div>
                <!--PRODUCT REVIEW TABS END-->
                <div class="input-container">
                    <form action="{% url 'book' object.slug %}" method="post">
                    {% csrf_token %}
                        <div class="input-field">
                            Name: <input type="text" name="name" placeholder="Ivan">
                        </div>
                        <div class="input-field">
                            Email: <input type="text" name="email" placeholder="IvanMahno@gmail.com">
                        </div>
                        <div class="input-field">
                            Comment: <textarea type="text" name="comment" placeholder="Interesting book..."></textarea>
                        </div>
<!--                        <div>-->
<!--                            Your rating: <div class="rateyo"-->
<!--                                 data-rateyo-rating="{{ review.rating }}"-->
<!--                                 data-rateyo-num-stars="5"></div>-->
<!--                        </div>-->
                        <div class="input-field">
                            Your rating: <input type="text" name="rating" placeholder="From 1 of 5">
                        </div>
                        <br>
                        <button type="submit" class="add-to-cart">Review</button>
                    </form>
                </div>
                <!--RELATED PRODUCTS START-->
                <div class="lib-related-products">
                    <h2>Related Books</h2>
                    <div class="row">
                        <!--PRODUCT GRID START-->
                        {% for book in related_books %}
                        <div class="col-md-3 col-sm-6">
                            <div class="best-seller-pro">
                                 <figure>
                                    <img src="{{ book.img.url }}" alt="{{ book.name }}"
                                        style="width: 201px; height:298px;">
                                 </figure>
                        <div class="kode-text">
                            <h3><a href="{% url 'book' book.slug %}#">{{ book.name | truncatechars:20 }}</a></h3>
                        </div>
                        <div class="kode-caption">
                            <h3>{{ book.name | truncatechars:80 }}</h3>
                            <div class="rating">
<span>☆</span><span>☆</span><span>☆</span><span>☆</span><span>☆</span>
</div>
                            <p>{{ book.authors.all | cut:"<QuerySet [<Author: " | cut:">]>" | cut:"<QuerySet []>"}}</p>
                            <a href="{% url 'book' book.slug %}#" class="add-to-cart">View</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!--PRODUCT GRID END-->
                    </div>
                </div>
                <!--RELATED PRODUCTS END-->
            </div>
        </div>
    </div>
</div>
<section class="kode-uptodate">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<h2>stay up-to-dated</h2>
				</div>
				<div class="col-md-8">
					<div class="row">
						<div class="col-md-3">
							<div class="social-icons">
								<ul>
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
								</ul>
							</div>
						</div>
						<div class="col-md-9">
							<div class="input-container">
								<input type="text" placeholder="Your E-mail Address" id="sub-2">
								<button>Subscribe</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock main %}

templates/catalog.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<div class="kode-content padding-tb-50">
    <div class="container">
        <div class="row">
            {% include 'search_left_bar.html' %}
            <div class="col-md-9">
                <h1>Books about {{ object.name }}</h1>
                <div class="row">
                    <!--BOOK LISTING START-->
                    {% for book in book_list %}
                    <div class="col-md-4 col-sm-6">
                        <div class="books-listing-4">
                            <div class="kode-thumb">
                                <a href="{% url 'book' book.slug %}#"><img src="{{ book.img.url }}"
                                    style="width: 201px; height:298px;"></a>
                            </div>
                            <div class="kode-text">
                                <h3><a href="{% url 'book' book.slug %}#">{{ book.name | truncatechars:12 }}</a></h3>
                            </div>
                            <div class="book-price">
                                <div class="rating">
                                    <span>☆</span><span>☆</span><span>☆</span><span>☆</span><span>☆</span>
                                </div>
                            </div>
                            <a href="{% url 'book' book.slug %}#" class="add-to-cart">View</a>
                        </div>
                    </div>
                    {% endfor %}
                    <!--BOOK LISTING END-->
                    {% include 'paginator.html' %}
                </div>
            </div>
        </div>

    </div>
</div>
<section class="kode-uptodate">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>stay up-to-dated</h2>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-3">
                        <div class="social-icons">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="input-container">
                            <input type="text" placeholder="Your E-mail Address" id="sub-2">
                            <button>Subscribe</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock main %}

templates/footer.html
<footer class="footer-2">
    <div class="container">
        <div class="lib-copyrights">
            <p>Copyrights © 2015-16 KodeForest. All rights reserved</p>
            <div class="social-icon">
                <ul>
                    <li><a href="#" data-toggle="tooltip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" data-toggle="tooltip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="#" data-toggle="tooltip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" data-toggle="tooltip" title="Tumblr"><i class="fa fa-tumblr"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}

<header class="header-1">
    <div class="logo-container">
        <div class="container">
            <!--LOGO START-->
            <div class="logo">
                <a href="{% url 'home' %}"><img src="{% static 'images/logo-2.png' %}" alt=""></a>
            </div>
            <!--LOGO END-->
            <div class="kode-navigation">
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="#">Categories</a>
                        <ul>
                            {% for cat in categories %}
                            <li><a href="{% url 'category' cat.slug %}">{{ cat.name | truncatechars:30 }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="last"><a href="#">Contact Us</a></li>
                </ul>
            </div>
            <div id="kode-responsive-navigation" class="dl-menuwrapper">
                <button class="dl-trigger">Open Menu</button>
                <ul class="dl-menu">
                    <li class="menu-item kode-parent-menu"><a href="{% url 'home' %}">Home</a></li>
                    <li class="menu-item kode-parent-menu last"><a href="#">Categories</a>
                        <ul class="dl-submenu">
                            {% for cat in categories %}
                            <li><a href="{% url 'home' %}">{{ cat.name | truncatechars:26 }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="last"><a href="#">Contact Us</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>

templates/paginator.html
{% if is_paginated %}

<nav>
  <ul class="pagination">
    <li>
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      {% else %}
      <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      </a>
    </li>
    {% for i in paginator.page_range %}
        {% if forloop.counter|add:7 > page_obj.number and forloop.counter < page_obj.number|add:11 %}
            {% if page_obj.number == i %}
            <li class="active"><a href="?page={{ i }}" class="single-btn">{{ i }}</a></li>
            {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endif %}
    {% endfor %}
    <li>
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      {% else %}
      <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      </a>
    </li>
  </ul>
</nav>

{% endif %}

templates/search_left_bar.html
<div class="col-md-3 sidebar">
    <!--SEARCH WIDGET START-->
    <div class="widget widget-search">
        <h2>Search</h2>
        <div class="input-container">
            <form action="{% url 'search' %}" >
                <div class="input-field">
                    <input type="text" name="q" placeholder="Search Here...">
                   <button class="btn" type="submit" name="action">Search</button>
                </div>
            </form>
        </div>
    </div>
    <!--SEARCH WIDGET END-->
    <!--CATEGORY WIDGET START-->
    <div class="widget widget-categories">
        <h2>Authors</h2>
        <ul>
            {% for author in order_authors %}
            <li><a href="?author={{ author.slug }}">{{ author.name | truncatechars:35 }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <!--CATEGORY WIDGET END-->
</div>

templates/search_section.html
<div class="search-section">
    <div class="container">
        <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="index-1.html#Basic" aria-controls="Basic" role="tab" data-toggle="tab">Basic</a></li>
            <li role="presentation"><a href="index-1.html#Publications" aria-controls="Publications" role="tab" data-toggle="tab">Publications</a></li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="Basic">
                <div class="form-container">
                    <div class="row">
                        <form action="{% url 'search' %}" >
                            <div class="col-md-9 col-sm-4">
                                <input type="text" name="q" placeholder="Title of the book">
                            </div>
                        <div class="col-md-3 col-sm-12">
                            <button class="btn" type="submit" name="action">Search Book</button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane" id="Publications">
                <div class="form-container">
                    <div class="row">
                        <form action="{% url 'search-data' %}" >
                            <div class="col-md-9 col-sm-4">
                                <input type="text" name="q" placeholder="Publication date">
                            </div>
                        <div class="col-md-3 col-sm-12">
                            <button class="btn" type="submit" name="action">Search Date</button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
          </div>
    </div>
</div>